version: '3.8'
services:
  postgres:
    image: postgres:16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
  pgadmin:
    image: dpage/pgadmin4:8.4
    depends_on:
      - postgres
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    volumes:
      - ${KEYCLOAK_VOLUMES_REAL_PATH}
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: ${KEYCLOAK_IMPORT}
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    command:
      - start-dev
      - --import-realm
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - postgres
  project-watcher-eureka:
    container_name: project-watcher-eureka
    image: dylams/project-watcher-eureka
    #    env_file:
    #      - ./env/dev.env
    build: .
    ports:
      - ${EUREKA_SERVICE_SERVER_PORT}:8761
    restart: always
    depends_on:
      - postgres
      - keycloak
  project-watcher-config:
    container_name: project-watcher-config
    image: dylams/project-watcher-config
    #    env_file:
    #      - ./env/dev.env
    build: .
    ports:
      - ${CONFIG_SERVICE_SERVER_PORT}:8888
    restart: always
    depends_on:
      - project-watcher-eureka
  project-watcher-gateway:
    container_name: project-watcher-gateway
    image: dylams/project-watcher-gateway
    #    env_file:
    #      - ./env/dev.env
    build: .
    ports:
      - ${GATEWAY_SERVICE_SERVER_PORT}:8762
    restart: always
    depends_on:
      - postgres
      - keycloak
      - project-watcher-config
      - project-watcher-eureka
  project-watcher-mangas:
    container_name: project-watcher-mangas
    image: dylams/project-watcher-mangas
    #    env_file:
    #      - ./env/dev.env
    build: .
    ports:
      - ${MANGAS_SERVICE_SERVER_PORT}:7001
    restart: always
    depends_on:
      - postgres
      - keycloak
      - project-watcher-config
      - project-watcher-eureka
      - project-watcher-gateway
volumes:
  postgres_data:
