spring:
  application:
    name: ${EUREKA_SERVICE_SPRING_APPLICATION_NAME}
  profiles:
    active: ${COMMON_SERVICE_SPRING_PROFILES_ACTIVE}
server:
  port: ${EUREKA_SERVICE_SERVER_PORT} # Le port sur lequel Eureka va écouter

eureka:
  client:
    registerWithEureka: false # ne pas s'enregistrer avec le service Eureka
    fetchRegistry: false # pas de cache local du registry
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_EUREKA_SERVER_SERVICEURL_DEFAULTZONE}
