server:
  port: ${GATEWAY_SERVICE_SERVER_PORT}
spring:
  devtools:
    livereload:
      port: ${GATEWAY_SERVICE_SPRING_DEVTOOLS_LIVERELOAD_PORT}
  application:
    name: ${GATEWAY_SERVICE_SPRING_APPLICATION_NAME}
  profiles:
    active: ${COMMON_SERVICE_SPRING_PROFILES_ACTIVE}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COMMON_SERVICE_SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI}
          user-name-attribute: preferred_username

  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      default-filters:
        - TokenRelay
      routes:
        - id: ${MANGAS_SERVICE_SPRING_APPLICATION_NAME}
          uri: ${GATEWAY_SERVICE_SPRING_CLOUD_GATEWAY_ROUTES_MANGAS_SERVICE_URI}
          predicates:
            - Path=${GATEWAY_SERVICE_SPRING_CLOUD_GATEWAY_ROUTES_MANGAS_SERVICE_PREDICATES_PATH}
    config:
      name: ${GATEWAY_SERVICE_SPRING_APPLICATION_NAME}
      uri: ${COMMON_SERVICE_SPRING_CLOUD_CONFIG_URI}
      username: ${COMMON_SPRING_CLOUD_CONFIG_USERNAME}
      password: ${COMMON_SPRING_CLOUD_CONFIG_PASSWORD}
      fail-fast: ${COMMON_SPRING_CLOUD_CONFIG_FAILFAST}
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${COMMON_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

