server:
  port: ${CONFIG_SERVICE_SERVER_PORT}
spring:
  application:
    name: ${CONFIG_SERVICE_SPRING_APPLICATION_NAME}
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
          clone-on-start: true
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULTLABEL}
          private-key: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PRIVATE_KEY}
  security:
    user:
      name: ${COMMON_SPRING_CLOUD_CONFIG_USERNAME}
      password: ${COMMON_SPRING_CLOUD_CONFIG_PASSWORD}
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${COMMON_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    registry-fetch-interval-seconds: 5
